import { Button } from "@material-tailwind/react";
import Head from "next/head";
import React from "react";

const HomePage = () => {
  return (
    <div>
      <Head>
        <title>AT - HOME</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>This is home page</h1>

        <Button>Click Me</Button>
      </main>
    </div>
  );
};

export default HomePage;
